CREATE TABLE PRODUTOS(
PRODUTOS_ID INT PRIMARY KEY,
NOME_PDT CHAR(1000) NOTNULL,
CATEGORIA NAME NOTNULL,
VALOR FLOAT NOTNULL,
TAMANHO CHAR(1000) NOTNULL
);


CREATE TABLE CLIENTE(
CLIENTE_ID INT PRIMARY KEY,
NOME NAME NOTNULL,
DATA DATE NOTNULL,
EMAIL CHAR(1000)
