CREATE TABLE PRODUTOS (
    PRODUTOS_ID INT PRIMARY KEY,
    NOME_PDT VARCHAR(150) NOT NULL,
    CATEGORIA VARCHAR(50) NOT NULL,
    MATERIAL VARCHAR(50) NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    TAMANHO VARCHAR(50) NOT NULL
);

INSERT INTO PRODUTOS
(PRODUTOS_ID, NOME_PDT, CATEGORIA, MATERIAL, VALOR, TAMANHO)
VALUES
(1, 'Protetor de carregador', 'uso pessoal', 'PLA PREMIUM', 24.90, '8x2.2x1.8cm');

CREATE TABLE CLIENTE (
    CLIENTE_ID INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DATA DATE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    CEP VARCHAR(9) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    ENDER VARCHAR(150) NOT NULL,
    NCASA INT NOT NULL,
    COMPLE VARCHAR(50),
    CITY VARCHAR(50) NOT NULL,
    UF CHAR(2) NOT NULL,
    OBS TEXT
);

INSERT INTO CLIENTE
(CLIENTE_ID, NOME, DATA, EMAIL, CPF, CEP, TELEFONE, ENDER, NCASA, COMPLE, CITY, UF, OBS)
VALUES
(1, 'Pedro', '2010-03-10', 'pedro.balde@gmail.com', '111.526.426-19', '83702-050', '41 9666-1670', 'Rua Fernando Pinho de Azevedo', 49, 'casa preta', 'Araucária', 'PR', 'Cliente bom, educado, e bondoso.'),
(2, 'Pedro Ocanha', '2010-04-01', 'pedro.ocanha@gmail.com', '222.989.432-89','80020-310' ,'41 95432-7032', 'Rua XV de Novembro', 32, 'Apartamento cor marrom beje', 'Curitiba', 'PR', 'Paga bem, preciso de mais clientes.');
