CREATE TABLE PRODUTOS(
PRODUTOS_ID INT PRIMARY KEY,
NOME_PDT CHAR(1000) NOTNULL,
CATEGORIA TEXT NOTNULL,
MATERIAL TEXT NOTNULL,
VALOR FLOAT NOTNULL,
TAMANHO CHAR(1000) NOTNULL
);


CREATE TABLE CLIENTE(
CLIENTE_ID INT PRIMARY KEY,
NOME TEXT NOTNULL,
DATA DATE NOTNULL,
EMAIL CHAR(1000) NOTNULL,
CPF INT(11) NOTNULL,
CEP INT(8) NOTNULL,
TELEFONE INT(11) NOTNULL,
ENDER CHAR(1000) NOTNULL,
NCASA INT NOTNULL,
COMPLE CHAR(100) NOTNULL,
CITY TEXT NOTNULL,
UF CHAR(2) NOTNULL,
OBS TEXT NOTNULL
);
